sudo: required

services:
  - docker

before_install:
  - echo "Building image with version $(cat VERSION)"
  - docker build -t sherpc/maslo:$(cat VERSION) .
  - docker images

script:
  - echo "OK"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "Pushing to docker hub"
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sherpc/maslo:$(cat VERSION);
    fi
