sudo: required

services:
  - docker

script:
  - echo "Building image with version $(cat VERSION)"
  - docker build -t sherpc/maslo:$(cat VERSION) .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "Pushing to docker hub"
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sherpc/maslo:$(cat VERSION);
    fi
