sudo: required

services:
  - docker

before_install:
  - echo "Building image with version $(cat VERSION)"
  - docker build -t $(cat VERSION) .
  - docker images

script:
  - echo "OK"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo -e "Pushing to docker hub $(cat VERSION)\n"
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $(cat VERSION);
    fi
