version: '2'
services:
  app:
    image: sherpc/maslo:0.14
    volumes:
      - /tmp/maslo:/mnt/data
      - /tmp/keys:/mnt/keys
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WAL_PATH=/mnt/data/wal.csv
      - COUNTER_PATH=/mnt/data/counter
      - SENT_LOG_PATH=/mnt/data/sent_emails.log
      - KEYS_PATH=/mnt/keys/
      - TIMEZONE_CORRECTION=3
      - RUN_INPUT_FETCHER_EVERY=0.3s
      - RUN_GOOGLE_FETCHER_EVERY=1s
      - LOG_DEBUG=true
    ports:
      - "4567:4567"
    logging:
      driver: json-file
  tank:
    image: direvius/yandex-tank
    volumes:
      - /Users/a.sher/Sources/maslyanitsa:/var/loadtest
      - $HOME/.ssh:/root/.ssh
    network_mode: "host"
